### ISSUE TITLE
روی لاراول 5.5 اجرا نمیشه

### ISSUE THREAD

**Issue by webineh** [MahdiMajidzadeh/laravel-kavenegar#5]
روی لاراول 5.5 اجرا نمیشه

**Comment by MahdiMajidzadeh** [comment]
چه خطایی میده 
چون من الان دارم استفاده می کنم رو همین ورژن

**Comment by webineh** [comment]
مجدد تست میکنم

**Comment by webineh** [comment]
بعد از نصب و اضافه کردن 
provider 
دستور 
php artisan vendor publish
به بعد با خطای syntax
مواجه میشه

**Comment by webineh** [comment]
سلام  . شما 
 Facde
 ایجاد نکرده اید 
و استفاده از خط کد زیر 
`$sms = new SMS();
`
خطا میده 

Class 'SMS' not found

**Comment by MahdiMajidzadeh** [comment]
می تونید پول ریکوست بزنین؟

**Comment by webineh** [comment]
نه من دقیقا نمیدونم معماری کد چطوره
اما این مشکل را داره

**Comment by vahidalvandi** [comment]
این باگ بیا با هم برطرف کنیم . چون از 
guzzle 
استفاده کردی خوشم اومده ازش
